// Array of 300 common 3-letter words
export const threeLetterWords = [
    "the", "and", "for", "are", "but", "not", "you", "all", "can", "her",
    "was", "one", "our", "out", "day", "get", "has", "him", "his", "how",
    "man", "new", "now", "old", "see", "two", "way", "who", "boy", "did",
    "its", "let", "put", "say", "she", "too", "use", "dad", "mom", "may",
    "big", "car", "dog", "cat", "run", "sit", "top", "hot", "sun", "red",
    "yes", "add", "age", "ago", "air", "arm", "art", "bad", "bag", "bat",
    "bed", "bet", "bit", "box", "bus", "buy", "cup", "cut", "dry", "ear",
    "eat", "egg", "end", "eye", "far", "fat", "few", "fix", "fly", "fun",
    "gas", "god", "got", "gun", "guy", "hat", "hit", "ice", "job", "key",
    "kid", "law", "lay", "leg", "lie", "lot", "low", "map", "mix", "net",
    "nor", "off", "oil", "own", "pay", "pen", "pet", "pop", "pot", "row",
    "sad", "sea", "set", "sex", "sin", "sir", "sky", "son", "tan", "tax",
    "tea", "ten", "tie", "tip", "toy", "try", "war", "win", "yet", "zoo",
    "act", "aim", "any", "arc", "ask", "ate", "ban", "bar", "bay", "bee",
    "bid", "bin", "bow", "bun", "cab", "cam", "cap", "cod", "cop", "cow",
    "cry", "dam", "den", "dew", "dig", "dim", "din", "dip", "doc", "dot",
    "due", "dug", "dye", "elm", "era", "eve", "fan", "fed", "fee", "fin",
    "fir", "fit", "fog", "fry", "fur", "gap", "gel", "gem", "gin", "gum",
    "ham", "hen", "hex", "hid", "hog", "hop", "hub", "hug", "hut", "ink",
    "inn", "ion", "jam", "jar", "jaw", "jet", "jog", "joy", "lab", "lad",
    "lap", "led", "log", "mad", "mat", "met", "mid", "mod", "mud", "nap",
    "nod", "non", "nut", "oak", "oar", "odd", "ore", "owe", "owl", "pad",
    "pan", "paw", "pea", "peg", "pie", "pig", "pin", "pit", "pod", "pub",
    "ram", "ran", "rap", "rat", "raw", "ray", "rib", "rid", "rim", "rip",
    "rob", "rod", "rot", "rub", "rug", "rum", "sac", "sat", "saw", "shy",
    "sip", "sis", "ski", "sly", "sob", "sod", "sow", "spa", "spy", "sub",
    "sue", "sum", "tab", "tag", "tap", "tar", "ten", "the", "tow", "tub",
    "tug", "van", "vet", "via", "vie", "wag", "wax", "web", "wed", "wet",
    "wig", "wit", "won", "wow", "yak", "yam", "yen", "yep", "zip", "ape",
    "axe", "awe", "beg", "bog", "bug", "bum", "cob", "cot", "cue", "dad"
  ];
  
  // Array of 300 common 4-letter words
 export const fourLetterWords = [
    "that", "with", "have", "this", "will", "your", "from", "they", "been",
    "more", "when", "time", "very", "come", "here", "just", "like", "long",
    "make", "many", "over", "such", "take", "than", "them", "well", "only",
    "back", "call", "came", "each", "find", "good", "hand", "high",
    "keep", "last", "left", "life", "live", "look", "made", "most", "much",
    "must", "name", "need", "next", "open", "part", "play", "said", "same",
    "seem", "show", "side", "some", "tell", "then", "turn", "used", "want",
    "week", "went", "were", "what", "work", "year", "also", "area", "away",
    "best", "book", "both", "case", "door", "down", "even", "face", "fact",
    "feel", "give", "help", "home", "into", "know", "land", "late", "line",
    "love", "mean", "move", "near", "once", "real", "read", "room", "sure",
    "able", "acts", "aged", "ages", "aims", "arms", "army", "baby", "back",
    "ball", "band", "bank", "base", "bear", "beat", "beer", "bell", "belt",
    "bend", "bill", "bird", "blow", "blue", "boat", "body", "bold", "bomb",
    "bond", "bone", "boom", "born", "boss", "bowl", "boys", "busy", "cafe",
    "cake", "calm", "camp", "card", "care", "cars", "cash", "cast", "cell",
    "chat", "chip", "city", "club", "coal", "coat", "code", "cold", "come",
    "cook", "cool", "copy", "core", "corn", "cost", "crew", "crop", "dark",
    "data", "date", "dawn", "days", "dead", "deal", "dear", "debt", "deep",
    "deer", "desk", "diet", "dirt", "disc", "disk", "does", "done", "dose",
    "draw", "drew", "drop", "drug", "drum", "dual", "duck", "dumb", "dump",
    "dust", "duty", "each", "earn", "ease", "east", "easy", "edge", "edit",
    "else", "emit", "epic", "exit", "eyes", "fail", "fair", "fall", "fame",
    "farm", "fast", "fate", "fear", "feed", "feet", "fell", "felt", "file",
    "fill", "film", "fine", "fire", "firm", "fish", "fist", "five", "flag",
    "flat", "fled", "flee", "flew", "flow", "folk", "fond", "food", "foot",
    "ford", "fork", "form", "fort", "four", "free", "from", "fuel", "full",
    "fund", "gain", "game", "gang", "gate", "gave", "gear", "gene", "gift",
    "girl", "glad", "goal", "goes", "gold", "golf", "gone", "grab", "gran",
    "gray", "grew", "grey", "grid", "grin", "grip", "grow", "gulf", "hair"
  ];
  
  // Array of 300 common 5-letter words
 export const fiveLetterWords = [
    "about", "after", "again", "could", "every", "first", "found", "great",
    "house", "large", "learn", "never", "other", "place", "point",
    "right", "small", "still", "their", "there", "these", "thing", "think",
    "three", "under", "water", "where", "which", "while", "world", "would",
    "write", "above", "being", "black", "bring", "cause", "child", "close",
    "early", "going", "group", "happy", "heart", "light", "might", "money",
    "month", "night", "often", "order", "paper", "party", "power", "quite",
    "round", "since", "sound", "space", "start", "state", "story", "study",
    "table", "today", "total", "trade", "truth", "until", "white", "whole",
    "woman", "young", "added", "alone", "angry", "began", "board", "books",
    "bread", "break", "brown", "build", "carry", "chair", "clean", "clear",
    "death", "doing", "drink", "earth", "eight", "enjoy", "enter", "equal",
    "event", "field", "fight", "final", "floor", "force", "actor", "acute",
    "admit", "adopt", "adult", "after", "agent", "agree", "ahead", "alarm",
    "album", "alert", "align", "alike", "alive", "allow", "along", "alter",
    "angel", "angle", "apart", "apple", "apply", "arena", "argue", "arise",
    "array", "arrow", "aside", "asset", "avoid", "awake", "award", "aware",
    "badly", "baker", "bases", "basic", "beach", "began", "belly", "below",
    "bench", "berry", "birth", "blade", "blame", "blank", "blend", "bless",
    "blind", "block", "blood", "bloom", "blues", "blunt", "blush", "bonus",
    "boost", "booth", "bound", "brain", "brand", "brave", "brick", "bride",
    "brief", "broad", "broke", "brush", "buddy", "build", "built", "bunch",
    "burst", "cabin", "cable", "cache", "canal", "candy", "cards", "cargo",
    "catch", "cause", "chain", "chaos", "charm", "chart", "chase", "cheap",
    "check", "cheek", "cheer", "chess", "chest", "chief", "china", "chose",
    "chunk", "civic", "civil", "claim", "class", "clock", "clone", "cloth",
    "cloud", "clown", "coach", "coast", "couch", "count", "court", "cover",
    "crack", "craft", "crash", "crazy", "cream", "creek", "crime", "crisp",
    "cross", "crowd", "crown", "crude", "cruel", "crush", "curve", "cycle",
    "daily", "dairy", "dance", "dated", "dealt", "debut", "decay", "decor"
  ];
  
  // Array of 300 common 6-letter words
 export const sixLetterWords = [
    "people", "before", "should", "really", "little", "number", "called",
    "always", "around", "change", "coming", "family", "figure", "friend",
    "ground", "having", "looked", "mother", "office", "person", "public",
    "school", "second", "strong", "system", "better", "center", "course",
    "during", "enough", "father", "follow", "formed", "future",
    "giving", "happen", "headed", "higher", "remain", "leaves", "letter",
    "living", "making", "market", "matter", "member", "minute", "moment",
    "nature", "needed", "notice", "opened", "period", "please", "pretty",
    "reason", "record", "result", "return", "rights", "season", "simple",
    "single", "social", "source", "spring", "square", "street", "summer",
    "supply", "things", "though", "turned", "twenty", "winter", "wonder",
    "worked", "actual", "across", "action", "almost", "amount", "animal",
    "answer", "appear", "attack", "august", "beauty", "become",
    "behind", "belief", "beyond", "border", "bottle", "bottom", "branch",
    "bridge", "broken", "budget", "button", "camera", "absent", "absorb",
    "accent", "accept", "access", "accord", "acting", "active", "advice",
    "advise", "affair", "affect", "afford", "afraid", "agency", "agenda",
    "allied", "allows", "ancien", "anchor", "angels", "angels", "angler",
    "angles", "anyone", "anyway", "appeal", "apples", "arcade", "archer",
    "arrest", "arrive", "artist", "ashame", "asleep", "aspect", "aspire",
    "assert", "assess", "assign", "assist", "assume", "assure", "attach",
    "attain", "attend", "august", "author", "autumn", "avenue", "awaken",
    "awards", "babies", "backed", "bakery", "ballot", "banana", "bandit",
    "banker", "banner", "barely", "barrel", "basket", "battle", "beacon",
    "bearer", "beaten", "became", "behalf", "behave", "beings", "belong",
    "berlin", "beside", "betray", "beyond", "biased", "bishop", "bitter",
    "blamed", "blanks", "blazer", "bleach", "blight", "blocks", "blonde",
    "bloody", "blosso", "boards", "boasts", "bodies", "boiler", "boldly",
    "bomber", "bonded", "booked", "boots", "boring", "borrow", "bosses",
    "bother", "bought", "bounce", "bounds", "bowled", "boxing", "branch"
  ];
  
  // Array of 300 common 7-letter words
  export const sevenLetterWords = [
    "because", "through", "another", "between", "without", "against", "nothing",
    "however", "present", "several", "whether", "himself", "already", "article",
    "brought", "certain", "company", "control", "country", "current", "evening",
    "general", "getting", "history", "instead", "morning", "natural",
    "perhaps", "problem", "program", "purpose", "receive", "service", "special",
    "subject", "support", "surface", "thought", "tonight", "towards", "village",
    "western", "written", "address", "amazing", "ancient", "applied", "becomes", "believe", "benefits", "beneath", "besides",
    "brother", "building", "business", "capital", "captain",
    "careful", "century", "changes", "chapter", "climate", "clothes", "collect", "college", "comfort", "command", "comment",
    "compare", "compete", "complex", "concept", "concern", "conduct", "confirm",
    "connect", "contain", "contest", "context", "correct", "council", "courage", "created", "culture",
    "customer", "ability", "absence", "absolut", "academy", "account", "accused",
    "achieve", "acquire", "actions", "adapted", "adopted", "advance", "advised",
    "affects", "affords", "african", "airline", "airport", "alcohol", "algebra",
    "allowed", "alright", "amended", "amounts", "amused", "analyst", "anatomy",
    "anxiety", "anybody", "applied", "appoint", "approve", "archive", "arguing",
    "arranged", "arrival", "article", "artists", "ashamed", "assault", "assumed",
    "assured", "athlete", "attempt", "attract", "auction", "authors", "average",
    "avoided", "awaking", "awarded", "awesome", "backing", "baggage", "balance",
    "balloon", "banking", "barrier", "battery", "bearing", "beating", "bedroom",
    "begging", "behaved", "belongs", "beneath", "benefit", "betting", "bicycle",
    "biggest", "billion", "binding", "biology", "blanket", "blasted", "blazing",
    "blessed", "blowing", "bonding", "booking", "borning", "bottles", "boulder",
    "bounded", "bowling", "bracket", "breaker", "brewing", "bridges", "briefed",
    "briefly", "brigade", "brighter", "broadly", "brother", "brought", "browser",
    "builder", "burning", "cabinet", "caliber", "calling", "camping", "capable",
    "caption", "capture", "careeer", "careful", "carrier", "carried", "casting",
    "catalog", "catches", "caution", "ceiling", "central", "chamber", "changed",
    "channel", "chapter", "charged", "charity", "charmed", "charter", "chasing",
    "cheaper", "cheated", "checked", "cheereed", "chicken", "choices", "choking",
    "chronic", "circuit", "citizen", "claimed", "classic", "cleared", "clicked"
  ];
  
  // Display the arrays
  console.log("3-Letter Words:", threeLetterWords.length, "words");
  console.log("4-Letter Words:", fourLetterWords.length, "words");
  console.log("5-Letter Words:", fiveLetterWords.length, "words");
  console.log("6-Letter Words:", sixLetterWords.length, "words");
  console.log("7-Letter Words:", sevenLetterWords.length, "words");